### ISSUE TITLE
Running SICER2 with biological replicate

### ISSUE THREAD

**Issue by cell101** [zanglab/SICER2#1]
Hi 
I'm trying to use SICER2 to ChIP peak calling
I have 2 biological replicates for TF-Myc   and 2 biological replicates for WT
TF-Myc-ChIP-rep1,         TF-Myc-ChIP-rep2, 
TF-Input_rep1,                TF-Input_rep2
WT-Myc-ChIP-rep1,        WT-Myc-ChIP-rep2, 
WT-Input_rep1,               WT-Input_rep2

My question is
1. is SICER2 possible to handle biological replicates or do I need to merge replicates and run SICER2?
 
2. to detect TF binding peak,  do I need to compare 
TF-Myc-ChIP  vs WT-Myc-ChIP  or
TF-Myc-ChIP  vs TF-Input ?

**Comment by czang** [comment]
1. SICER2 does not handle replicates automatically. You can either merge replicates and run SICER2 on the merged data files, or run SICER2 on each biological replicate separately. The latter is usually a better way, unless there is other evidence supporting that the replicates are similar enough.

2. What exactly do TF-Myc and WT-Myc mean? It depends on what biological question you are asking, or what analysis goal you want to achieve?

**Comment by cell101** [comment]
thank you for your reply 

for question 2
TF-Myc is Transcriprtion Factor genes tagged with Myc  and immunoprecipitated with anti-Myc 
WT-Myc is  immunoprecipitated with anti-Myc in Wild Type
Because there is no Myc in WT, theoritically, WT-Myc-ChIP does not have peaks
Input is total DNA used for input control
Because input is total DNA, TF-Input does not have any specific peak but basal level of read will be detected.

so I wonder which comparison would give a better peak calling
TF-Myc-ChIP vs WT-Myc-ChIP or
TF-Myc-ChIP vs TF-Input ?

I hope my post would help for your better understanding

**Comment by czang** [comment]
You can use sicer_df that takes into account for both WT and input.

Calling SICER with control libraries for differential peak calling.
sicer_df -t TF-Myc-ChIP.bed WT-Myc-ChIP.bed -c TF-Input.bed ET-Input.bed

**Comment by cell101** [comment]
great. thank you for your kind explanation.

ps. I hope that SCICER2 would support biological replicates in the near future

**Comment by czang** [comment]
Thanks for the feedback!
