### ISSUE TITLE
Bug when names of input treatment and control files are the same

### ISSUE THREAD

**Issue by AlexandreLaverre** [zanglab/SICER2#13]
Hello, 

Thanks for your work on SICER2 ! 
I just want to report a little bug. When the input treatment file and the input control file have the same name, even if they are in two different folders and the absolute paths are different, the last step of the program doesn't work and seems to consider the same number of reads on islands for both files.

Output of a first run where treatment and control have the same basename but different path:
Treatment = Mouse_GT_H3K27ac/accepted_hits_unique.bed
Control = Mouse_GT_control/accepted_hits_unique.bed
```
Calculating significance of candidate islands using the control library... 
ChIP library read count: 190020952
Control library read count: 96584843
Total number of chip reads on islands is: 33699190
Total number of control reads on islands is: 33699190
Identify significant islands using FDR criterion

Given significance 0.01 , there are 0 significant islands
```

Same run but when modifying the control file basename:
Treatment = Mouse_GT_H3K27ac/accepted_hits_unique.bed
Control = Mouse_GT_control/accepted_hits_unique_control.bed
```
ChIP library read count: 190020952
Control library read count: 96584843
Total number of chip reads on islands is: 84681739
Total number of control reads on islands is: 39116477
Identify significant islands using FDR criterion

Given significance 0.01 , there are 30015 significant islands
```

**Comment by JasonJiangs** [comment]
Hi, thanks for the issue! We will consider it in the next version.
