### ISSUE TITLE
Custom genome adding

### ISSUE THREAD

**Issue by El-Castor** [zanglab/SICER2#15]
Hi, 

I am trying your new version of sicer but when I tried to install my custom genome at the step were you suggest to do pip install -e at the bottom of the repo of SICER2 it dind't work, pip say that I have to give one arguments as you can see below :

```bash

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument


```

Do you have any suggestion ?

Thank a lot in advance

**Comment by El-Castor** [comment]
Sorry I find my error ...

**Comment by poflawless** [comment]
@El-Castor , Hi EI-Castor, Could you please what is going wrong? 
I have the same issue
