### ISSUE TITLE
SICER2 can't run~

### ISSUE THREAD

**Issue by freedog8** [zanglab/SICER2#3]
here is the screenshot
![image](https://user-images.githubusercontent.com/21093659/68298173-adab3700-00d3-11ea-9493-4604ed2570ec.png)

**Comment by jinyongyoo** [comment]
I believe that the main issue happens when sicer2 calls bedtools to covert the .bam file to .bed file. Can you try running bedtools on the .bam separately and seeing what happens? I've seen a similar error, so I'll be looking into this.

**Comment by jinyongyoo** [comment]
This bug has been fixed in version 1.0.1
